#!/usr/bin/env python3
"""Validate canonical AH vendor pricing and two-button guide navigation."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GUIDES_DIR = ROOT / "guides"
DATA_PATH = ROOT / "data" / "ah-vendor-sections.json"
INDEX_PATH = ROOT / "assets" / "ah-search-index.js"
AH_GUIDE_GLOB = "*ah-price-guide.html"


def fail(message: str) -> None:
    raise AssertionError(message)


def format_money(copper: int) -> str:
    gold, remainder = divmod(copper, 10_000)
    silver, copper = divmod(remainder, 100)
    parts: list[str] = []
    if gold:
        parts.append(f"{gold:,}g")
    if silver:
        parts.append(f"{silver}s")
    if copper or not parts:
        parts.append(f"{copper}c")
    return " ".join(parts)


def load_index() -> dict:
    source = INDEX_PATH.read_text(encoding="utf-8")
    match = re.fullmatch(
        r"/\* Generated by scripts/build-ah-search-index\.py\. Do not edit directly\. \*/\n"
        r"window\.AH_SEARCH_INDEX=(\{.*\});\n",
        source,
        re.DOTALL,
    )
    if not match:
        fail("Unexpected AH search-index wrapper")
    return json.loads(match.group(1))


def main() -> int:
    subprocess.run(
        [sys.executable, "scripts/render-ah-shared-sections.py", "--check"],
        cwd=ROOT,
        check=True,
    )

    config = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    catalog = config["catalog"]
    configured_guides = config["guides"]
    guide_paths = sorted(GUIDES_DIR.glob(AH_GUIDE_GLOB))
    if len(guide_paths) != 16:
        fail(f"Expected 16 AH guides, found {len(guide_paths)}")
    if len(configured_guides) != 10:
        fail(f"Expected 10 guides with vendor sections, found {len(configured_guides)}")

    used_keys: set[str] = set()
    for path in guide_paths:
        source = path.read_text(encoding="utf-8")
        nav_match = re.search(
            r"<!-- AH_SHARED_NAV_START -->\s*"
            r"<nav class=\"site-nav ah-guide-nav\" aria-label=\"Guide navigation\">"
            r"\s*<a class=\"guide-hub-link\" href=\"\.\./index\.html\">Guide Hub</a>"
            r"\s*<a class=\"ah-hub-link\" href=\"\.\./auction-house\.html\">AH Hub</a>"
            r"\s*</nav>\s*<!-- AH_SHARED_NAV_END -->",
            source,
        )
        if not nav_match:
            fail(f"{path.name}: missing canonical Guide Hub / AH Hub navigation")

        vendor_match = re.search(
            r"<!-- AH_VENDOR_SECTION_START -->\s*"
            r"<section class=\"common vendor-compact\" data-ah-template=\"vendor-convenience-v1\">"
            r"(.*?)</section>\s*<!-- AH_VENDOR_SECTION_END -->",
            source,
            re.DOTALL,
        )
        guide_config = configured_guides.get(path.name)
        if guide_config is None:
            if vendor_match:
                fail(f"{path.name}: unexpected vendor section")
            continue
        if not vendor_match:
            fail(f"{path.name}: missing canonical vendor section")

        section = vendor_match.group(1)
        vague_phrases = (
            "vendor + tip",
            "vendor + tiny tip",
            "vendor + tiny margin",
            "check ah",
            "market item, not simple vendor",
        )
        lowered = section.casefold()
        for phrase in vague_phrases:
            if phrase in lowered:
                fail(f"{path.name}: vague vendor phrase remains: {phrase}")

        expected_keys = guide_config["items"]
        actual_keys = re.findall(r'<tr data-vendor-key="([^"]+)">', section)
        if actual_keys != expected_keys:
            fail(f"{path.name}: vendor rows do not match canonical order")

        for key in expected_keys:
            used_keys.add(key)
            item = catalog[key]
            expected_target = format_money(int(item["target_copper"]))
            row_match = re.search(
                rf'<tr data-vendor-key="{re.escape(key)}">(.*?)</tr>',
                section,
                re.DOTALL,
            )
            if not row_match:
                fail(f"{path.name}: missing row for {key}")
            row = row_match.group(1)
            if f'<span class="vendor-target buyout">{expected_target}</span>' not in row:
                fail(f"{path.name}: wrong target for {item['name']}")

    if used_keys != set(catalog):
        fail("Vendor catalog and guide usage do not match")

    for key, item in catalog.items():
        target = int(item["target_copper"])
        if target <= 0:
            fail(f"{key}: target price must be positive")
        if item["source_type"] == "coin-vendor":
            cost = int(item["vendor_cost_copper"])
            count = int(item.get("vendor_buy_count", 1))
            if count <= 0 or cost % count:
                fail(f"{key}: invalid vendor bundle")
            if target < cost // count:
                fail(f"{key}: target price is below unit vendor cost")
        elif not item.get("source_cost_label"):
            fail(f"{key}: non-vendor source needs a cost label")

    exact_targets = {
        "goblin-machined-piston": "1,050g",
        "elementium-plated-exhaust-pipe": "1,575g",
        "deeprock-salt": "1g",
        "rune-thread": "75s",
    }
    for key, expected in exact_targets.items():
        actual = format_money(int(catalog[key]["target_copper"]))
        if actual != expected:
            fail(f"{key}: expected {expected}, found {actual}")

    combined = "\n".join(path.read_text(encoding="utf-8") for path in guide_paths)
    obsolete_labels = (
        "Jeweler's Setting",
        "Blank Parchment / basic vendor odds",
        "Design/vendor-bought basics",
        "vendor + tiny tip",
        "vendor + tiny margin",
        "vendor + tip",
    )
    for label in obsolete_labels:
        if label.casefold() in combined.casefold():
            fail(f"Obsolete vendor label remains: {label}")
    if "Bright Baubles" not in combined or ">5s each<" not in combined:
        fail("Bright Baubles summary price was not updated")

    index = load_index()
    for filename, guide in configured_guides.items():
        for key in guide["items"]:
            item = catalog[key]
            expected_target = format_money(int(item["target_copper"]))
            matches = [
                entry
                for entry in index["items"]
                if entry["name"] == item["name"]
                and entry["href"].startswith(f"./guides/{filename}#")
            ]
            if len(matches) != 1:
                fail(f"{filename}: expected one indexed {item['name']} row, found {len(matches)}")
            if matches[0]["target"] != expected_target:
                fail(
                    f"{filename}: indexed {item['name']} target is "
                    f"{matches[0]['target']}, expected {expected_target}"
                )

    northern_spices = [
        entry
        for entry in index["items"]
        if entry["name"] == "Northern Spices"
        and entry["href"].startswith(
            "./guides/fishing-cooking-materials-ah-price-guide.html#"
        )
    ]
    if len(northern_spices) != 1 or northern_spices[0]["target"] != "3g":
        fail("Northern Spices must remain one exact 3g market entry")

    print(
        "AH vendor pricing validation passed: "
        f"{len(catalog)} canonical items, {len(configured_guides)} priced sections, "
        "16 two-button guide navs."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
