#!/usr/bin/env python3
"""Validate canonical AH vendor pricing and two-button guide navigation."""

from __future__ import annotations

import json
import html
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GUIDES_DIR = ROOT / "guides"
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from ah_guides import active_guide_paths  # noqa: E402

DATA_PATH = ROOT / "data" / "ah-vendor-sections.json"
INDEX_PATH = ROOT / "assets" / "ah-search-index.js"


def fail(message: str) -> None:
    raise AssertionError(message)


def format_money(copper: int) -> str:
    if copper >= 10_000:
        copper = ((copper + 50) // 100) * 100
    gold, remainder = divmod(copper, 10_000)
    silver, copper = divmod(remainder, 100)
    parts: list[str] = []
    if gold:
        parts.append(f"{gold:,}g")
    if silver:
        parts.append(f"{silver}s")
    if copper or not parts:
        parts.append(f"{copper}c")
    return " ".join(parts)


def load_index() -> dict:
    source = INDEX_PATH.read_text(encoding="utf-8")
    match = re.fullmatch(
        r"/\* Generated by scripts/build-ah-search-index\.py\. Do not edit directly\. \*/\n"
        r"window\.AH_SEARCH_INDEX=(\{.*\});\n",
        source,
        re.DOTALL,
    )
    if not match:
        fail("Unexpected AH search-index wrapper")
    return json.loads(match.group(1))


def main() -> int:
    subprocess.run(
        [sys.executable, "scripts/render-ah-shared-sections.py", "--check"],
        cwd=ROOT,
        check=True,
    )

    config = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    catalog = config["catalog"]
    configured_guides = config["guides"]
    guide_paths = active_guide_paths(guides_dir=GUIDES_DIR)
    if len(guide_paths) != 19:
        fail(f"Expected 19 AH guides, found {len(guide_paths)}")
    if len(configured_guides) != 11:
        fail(f"Expected 11 vendor configurations, found {len(configured_guides)}")

    used_keys: set[str] = set()
    for path in guide_paths:
        source = path.read_text(encoding="utf-8")
        nav_match = re.search(
            r"<!-- AH_SHARED_NAV_START -->\s*"
            r"<nav class=\"site-nav ah-guide-nav\" aria-label=\"Guide navigation\">"
            r"\s*<a class=\"guide-hub-link\" href=\"\.\./index\.html\">Guide Hub</a>"
            r"\s*<a class=\"ah-hub-link\" href=\"\.\./auction-house\.html\">AH Hub</a>"
            r"\s*</nav>\s*<!-- AH_SHARED_NAV_END -->",
            source,
        )
        if not nav_match:
            fail(f"{path.name}: missing canonical Guide Hub / AH Hub navigation")

        vendor_match = re.search(
            r"<!-- AH_VENDOR_SECTION_START -->(.*?)<!-- AH_VENDOR_SECTION_END -->",
            source,
            re.DOTALL,
        )
        guide_config = configured_guides.get(path.name)
        if guide_config is None:
            if vendor_match:
                fail(f"{path.name}: unexpected vendor section")
            continue
        if guide_config.get("remove"):
            if vendor_match:
                fail(f"{path.name}: removed vendor section was rendered")
            continue
        if not vendor_match:
            fail(f"{path.name}: missing canonical vendor section")

        section = vendor_match.group(1)
        vague_phrases = (
            "vendor + tip",
            "vendor + tiny tip",
            "vendor + tiny margin",
            "check ah",
            "market item, not simple vendor",
        )
        lowered = section.casefold()
        for phrase in vague_phrases:
            if phrase in lowered:
                fail(f"{path.name}: vague vendor phrase remains: {phrase}")

        expected_keys = list(guide_config["items"])
        for restricted_section in guide_config.get("restricted_sections", []):
            expected_keys.extend(restricted_section["items"])
        actual_keys = re.findall(r'<tr data-vendor-key="([^"]+)"[^>]*>', section)
        if len(actual_keys) != len(expected_keys) or set(actual_keys) != set(expected_keys):
            fail(f"{path.name}: vendor rows do not match canonical membership")

        for key in expected_keys:
            used_keys.add(key)
            item = catalog[key]
            expected_target = format_money(int(item["target_copper"]))
            row_match = re.search(
                rf'<tr data-vendor-key="{re.escape(key)}"[^>]*>(.*?)</tr>',
                section,
                re.DOTALL,
            )
            if not row_match:
                fail(f"{path.name}: missing row for {key}")
            row = row_match.group(1)
            expected_quality = item.get("quality", "common")
            escaped_name = html.escape(item["name"])
            if f'<strong class="q-{expected_quality}">{escaped_name}</strong>' not in row:
                fail(f"{path.name}: wrong rarity class for {item['name']}")
            if '<div class="pricepair target">' not in row:
                fail(f"{path.name}: {item['name']} does not use the standard price box")
            if f'<span class="buyout">{expected_target}</span>' not in row:
                fail(f"{path.name}: wrong target for {item['name']}")
            expected_demand = item.get("demand", "Low")
            expected_demand_class = item.get("demand_class", "low")
            expected_badge = (
                f'<span class="demand {expected_demand_class}">{expected_demand}</span>'
            )
            if expected_badge not in row:
                fail(f"{path.name}: {item['name']} is missing its configured demand badge")
            if "<strong>Source / cost:</strong>" not in row:
                fail(f"{path.name}: {item['name']} is missing source cost in its notes")

    cost_only_keys = {
        key for key, item in catalog.items() if item.get("cost_only") is True
    }
    if used_keys != set(catalog) - cost_only_keys:
        fail("Rendered vendor rows must match the auctionable vendor catalog")
    for key in cost_only_keys:
        if catalog[key].get("auctionable") is not False:
            fail(f"{key}: cost-only vendor input must set auctionable=false")

    for key, item in catalog.items():
        if item.get("quality", "common") not in {"poor", "common", "uncommon", "rare", "epic", "legendary"}:
            fail(f"{key}: invalid item quality")
        target = int(item["target_copper"])
        if target <= 0:
            fail(f"{key}: target price must be positive")
        if item["source_type"] == "coin-vendor":
            cost = int(item["vendor_cost_copper"])
            count = int(item.get("vendor_buy_count", 1))
            if count <= 0 or cost % count:
                fail(f"{key}: invalid vendor bundle")
            if target < cost // count:
                fail(f"{key}: target price is below unit vendor cost")
        elif not item.get("source_cost_label"):
            fail(f"{key}: non-vendor source needs a cost label")

    exact_targets = {
        "salvaged-iron-golem-parts": "220g",
        "goblin-machined-piston": "1,050g",
        "elementium-plated-exhaust-pipe": "1,575g",
        "rune-thread": "75s",
    }
    for key, expected in exact_targets.items():
        actual = format_money(int(catalog[key]["target_copper"]))
        if actual != expected:
            fail(f"{key}: expected {expected}, found {actual}")

    combined = "\n".join(path.read_text(encoding="utf-8") for path in guide_paths)
    obsolete_labels = (
        "Jeweler's Setting",
        "Blank Parchment / basic vendor odds",
        "Design/vendor-bought basics",
        "vendor + tiny tip",
        "vendor + tiny margin",
        "vendor + tip",
    )
    for label in obsolete_labels:
        if label.casefold() in combined.casefold():
            fail(f"Obsolete vendor label remains: {label}")
    for removed_tool in ("Bright Baubles", "Virtuoso Inking Set", "Jeweler's Kit", "Simple Grinder"):
        if removed_tool in combined:
            fail(f"Removed profession-only vendor tool remains: {removed_tool}")

    index = load_index()
    for filename, guide in configured_guides.items():
        expected_keys = list(guide["items"])
        for restricted_section in guide.get("restricted_sections", []):
            expected_keys.extend(restricted_section["items"])
        for key in expected_keys:
            item = catalog[key]
            expected_target = format_money(int(item["target_copper"]))
            matches = [
                entry
                for entry in index["items"]
                if entry["name"] == item["name"]
                and entry["href"].startswith(f"./guides/{filename}#")
            ]
            if len(matches) != 1:
                fail(f"{filename}: expected one indexed {item['name']} row, found {len(matches)}")
            if matches[0]["target"] != expected_target:
                fail(
                    f"{filename}: indexed {item['name']} target is "
                    f"{matches[0]['target']}, expected {expected_target}"
                )

    northern_spices = [
        entry
        for entry in index["items"]
        if entry["name"] == "Northern Spices"
        and entry["href"].startswith(
            "./guides/fishing-cooking-materials-ah-price-guide.html#"
        )
    ]
    if len(northern_spices) != 1 or northern_spices[0]["target"] != "3g":
        fail("Northern Spices must remain one exact 3g market entry")

    skinning_source = (
        ROOT / "guides" / "skinning-leatherworking-materials-ah-price-guide.html"
    ).read_text(encoding="utf-8")
    vendor_block = skinning_source.split("<!-- AH_VENDOR_SECTION_START -->", 1)[1].split(
        "<!-- AH_VENDOR_SECTION_END -->", 1
    )[0]
    if "Deeprock Salt" in vendor_block or 'data-vendor-key="deeprock-salt"' in skinning_source:
        fail("Deeprock Salt must not appear in the vendor section")

    deeprock_salt = [
        entry
        for entry in index["items"]
        if entry["name"] == "Deeprock Salt"
        and entry["href"].startswith(
            "./guides/skinning-leatherworking-materials-ah-price-guide.html#"
        )
    ]
    if len(deeprock_salt) != 1 or deeprock_salt[0]["target"] != "1g":
        fail("Deeprock Salt must remain one exact 1g regular market entry")

    print(
        "AH vendor pricing validation passed: "
        f"{len(catalog)} canonical items, "
        f"{sum(not guide.get('remove') for guide in configured_guides.values())} rendered vendor blocks, "
        "19 two-button guide navs."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
