#!/usr/bin/env python3
"""Build the browser-ready addon catalog from data/addons.json."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "addons.json"
OUTPUT = ROOT / "assets" / "addon-catalog-data.js"


def build() -> str:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    compact = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (
        "/* Generated by scripts/build-addon-catalog.py. Do not edit directly. */\n"
        f"window.ADDON_CATALOG={compact};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the generated browser data is stale")
    args = parser.parse_args()
    output = build()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != output:
            print("Addon catalog browser data is stale. Run: python scripts/build-addon-catalog.py", file=sys.stderr)
            return 1
        print("Addon catalog browser data is current.")
        return 0
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    print(f"Wrote {len(payload['addons'])} addons to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
